package com.hamming.storim.client.panels;

import com.hamming.storim.client.listitem.TileSetListItem;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author jehamming
 */
public class RoomTileEditorPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomTileEditorViewPanel
     */
    public RoomTileEditorPanel(JPanel viewPanel) {
        this.ViewPanel = viewPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        ControlsPanel = new javax.swing.JPanel();
        cmbBackgroundTileset = new javax.swing.JComboBox<>();
        cmbBackgroundTiles = new javax.swing.JComboBox<>();
        btnApplyAll = new javax.swing.JButton();
        cbGrid = new javax.swing.JCheckBox();
        btnSaveToServer = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbForegroundTileset = new javax.swing.JComboBox<>();
        cmbForegroundTiles = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        chkForeground = new javax.swing.JCheckBox();
        chkBackground = new javax.swing.JCheckBox();
        radioBG = new javax.swing.JRadioButton();
        radioFG = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout ViewPanelLayout = new javax.swing.GroupLayout(ViewPanel);
        ViewPanel.setLayout(ViewPanelLayout);
        ViewPanelLayout.setHorizontalGroup(
                ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 602, Short.MAX_VALUE)
        );
        ViewPanelLayout.setVerticalGroup(
                ViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        btnApplyAll.setText("Apply to All");

        cbGrid.setText("Show Grid");

        btnSaveToServer.setText("Save to Server");

        chkForeground.setText("Foreground");

        chkBackground.setText("Background");

        radioBG.setText("Draw background");

        radioFG.setText("Draw Foreground");

        jLabel1.setText("Hold CTRL to delete!");

        javax.swing.GroupLayout ControlsPanelLayout = new javax.swing.GroupLayout(ControlsPanel);
        ControlsPanel.setLayout(ControlsPanelLayout);
        ControlsPanelLayout.setHorizontalGroup(
                ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                                .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator2)
                                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                                                .addComponent(chkBackground)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cmbForegroundTileset, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmbForegroundTiles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                                                                .addGroup(ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(btnApplyAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cmbBackgroundTiles, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cmbBackgroundTileset, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cbGrid)
                                                                        .addComponent(btnSaveToServer, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                                        .addComponent(jSeparator1)
                                                                        .addComponent(chkForeground)
                                                                        .addComponent(radioBG)
                                                                        .addComponent(radioFG)
                                                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())
        );
        ControlsPanelLayout.setVerticalGroup(
                ControlsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ControlsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(chkBackground)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBackgroundTileset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbBackgroundTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnApplyAll)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(chkForeground)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbForegroundTileset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbForegroundTiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioBG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioFG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbGrid)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(btnSaveToServer))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(ControlsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ControlsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ViewPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
    }// </editor-fold>


    // Variables declaration - do not modify
    private javax.swing.JPanel ControlsPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JButton btnApplyAll;
    private javax.swing.JButton btnSaveToServer;
    private javax.swing.JCheckBox cbGrid;
    private javax.swing.JCheckBox chkBackground;
    private javax.swing.JCheckBox chkForeground;
    private javax.swing.JComboBox<ImageIcon> cmbBackgroundTiles;
    private javax.swing.JComboBox<TileSetListItem> cmbBackgroundTileset;
    private javax.swing.JComboBox<ImageIcon> cmbForegroundTiles;
    private javax.swing.JComboBox<TileSetListItem> cmbForegroundTileset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton radioBG;
    private javax.swing.JRadioButton radioFG;
    // End of variables declaration

    public JButton getBtnApplyAll() {
        return btnApplyAll;
    }

    public JCheckBox getCbGrid() {
        return cbGrid;
    }

    public JButton getBtnSaveToServer() {
        return btnSaveToServer;
    }

    public JCheckBox getChkBackground() {
        return chkBackground;
    }

    public JCheckBox getChkForeground() {
        return chkForeground;
    }

    public JComboBox<ImageIcon> getCmbBackgroundTiles() {
        return cmbBackgroundTiles;
    }

    public JComboBox<TileSetListItem> getCmbBackgroundTileset() {
        return cmbBackgroundTileset;
    }

    public JComboBox<ImageIcon> getCmbForegroundTiles() {
        return cmbForegroundTiles;
    }

    public JComboBox<TileSetListItem> getCmbForegroundTileset() {
        return cmbForegroundTileset;
    }

    public JRadioButton getRadioBG() {
        return radioBG;
    }

    public JRadioButton getRadioFG() {
        return radioFG;
    }
}

